"""first revision

迁移 ID: 2e188b3f6e5b
父迁移: 
创建时间: 2024-06-11 20:22:47.888266

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2e188b3f6e5b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('nonebot_plugin_wwgachalogs',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nonebot_plugin_wwgachalogs_userinfo',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('playerid', sa.String(), nullable=False),
    sa.Column('recordid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('userid', name=op.f('pk_nonebot_plugin_wwgachalogs_userinfo')),
    info={'bind_key': 'nonebot_plugin_wwgachalogs'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nonebot_plugin_wwgachalogs_userinfo')
    # ### end Alembic commands ###
